# Generated by Django 5.2.1 on 2025-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(help_text="Time of patient's arrival at the facility.")),
                ('last_known_well_time', models.DateTimeField(blank=True, help_text='Last time the patient was known to be at their baseline state.', null=True)),
                ('age', models.IntegerField(help_text="Patient's age in years.")),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text="Patient's weight in kilograms.", max_digits=5)),
                ('systolic_bp', models.IntegerField(help_text='Systolic blood pressure (mmHg).')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic blood pressure (mmHg).')),
                ('blood_glucose', models.DecimalField(decimal_places=2, help_text='Blood glucose level (e.g., mg/dL or mmol/L - specify units as needed).', max_digits=5)),
                ('anticoagulant_status', models.CharField(choices=[('NONE', 'None'), ('CURRENT', 'Currently on anticoagulant'), ('RECENT', 'Recent anticoagulant use (within 48 hours)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Anticoagulant use status.', max_length=10)),
                ('anticoagulant_medication', models.CharField(blank=True, help_text='Specific anticoagulant medication (if applicable).', max_length=100, null=True)),
                ('last_anticoagulant_dose', models.DateTimeField(blank=True, help_text='Date and time of last anticoagulant dose (if applicable).', null=True)),
            ],
            options={
                'verbose_name': 'Patient Record',
                'verbose_name_plural': 'Patient Records',
                'ordering': ['-arrival_time'],
            },
        ),
    ]
