# Generated by Django 5.2.1 on 2025-05-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrokeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_time', models.DateTimeField(auto_now_add=True, help_text='Time when this assessment was recorded.')),
                ('be_fast_balance', models.BooleanField(default=False, help_text='Sudden loss of balance or coordination.')),
                ('be_fast_eyes', models.BooleanField(default=False, help_text='Sudden blurred vision or loss of vision in one or both eyes.')),
                ('be_fast_face_drooping', models.BooleanField(default=False, help_text='Face drooping or numbness on one side.')),
                ('be_fast_arm_weakness', models.BooleanField(default=False, help_text='Arm weakness or numbness in one arm.')),
                ('be_fast_speech_difficulty', models.BooleanField(default=False, help_text='Speech difficulty or slurred speech.')),
                ('be_fast_time_to_call', models.BooleanField(default=False, help_text='Time to call emergency services (sudden onset of any symptom).')),
                ('be_fast_plus_other', models.BooleanField(default=False, help_text='Other sudden severe headache or confusion.')),
                ('nihss_1a_loc_alert', models.IntegerField(blank=True, help_text='NIHSS 1a: Level of Consciousness (Alertness).', null=True)),
                ('nihss_1b_loc_questions', models.IntegerField(blank=True, help_text='NIHSS 1b: Level of Consciousness (Questions).', null=True)),
                ('nihss_1c_loc_commands', models.IntegerField(blank=True, help_text='NIHSS 1c: Level of Consciousness (Commands).', null=True)),
                ('nihss_2_best_gaze', models.IntegerField(blank=True, help_text='NIHSS 2: Best Gaze.', null=True)),
                ('nihss_3_visual_field', models.IntegerField(blank=True, help_text='NIHSS 3: Visual Field.', null=True)),
                ('nihss_4_facial_palsy', models.IntegerField(blank=True, help_text='NIHSS 4: Facial Palsy.', null=True)),
                ('nihss_5a_motor_left_arm', models.IntegerField(blank=True, help_text='NIHSS 5a: Motor Left Arm.', null=True)),
                ('nihss_5b_motor_right_arm', models.IntegerField(blank=True, help_text='NIHSS 5b: Motor Right Arm.', null=True)),
                ('nihss_6a_motor_left_leg', models.IntegerField(blank=True, help_text='NIHSS 6a: Motor Left Leg.', null=True)),
                ('nihss_6b_motor_right_leg', models.IntegerField(blank=True, help_text='NIHSS 6b: Motor Right Leg.', null=True)),
                ('nihss_7_limb_ataxia', models.IntegerField(blank=True, help_text='NIHSS 7: Limb Ataxia.', null=True)),
                ('nihss_8_sensory', models.IntegerField(blank=True, help_text='NIHSS 8: Sensory.', null=True)),
                ('nihss_9_best_language', models.IntegerField(blank=True, help_text='NIHSS 9: Best Language.', null=True)),
                ('nihss_10_dysarthria', models.IntegerField(blank=True, help_text='NIHSS 10: Dysarthria.', null=True)),
                ('nihss_11_extinction_inattention', models.IntegerField(blank=True, help_text='NIHSS 11: Extinction and Inattention.', null=True)),
                ('ct_scan_time', models.DateTimeField(blank=True, help_text='Time of CT scan completion.', null=True)),
                ('hemorrhage_present', models.BooleanField(default=False, help_text='Indicates if hemorrhage is present on imaging.')),
                ('aspects_score', models.IntegerField(blank=True, help_text='ASPECTS score (0-10) for ischemic changes. Lower score indicates more severe ischemia.', null=True)),
                ('lvo_status', models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('UNKNOWN', 'Unknown')], default='NOT_ASSESSED', help_text='Status of Large Vessel Occlusion.', max_length=15)),
                ('lvo_location', models.CharField(blank=True, help_text='Location of LVO (e.g., ICA, M1, M2).', max_length=100, null=True)),
                ('tpa_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('CONTRAINDICATED', 'Contraindicated'), ('PENDING', 'Pending Assessment')], default='PENDING', help_text='Eligibility for tPA (tissue plasminogen activator).', max_length=15)),
                ('thrombectomy_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('CONTRAINDICATED', 'Contraindicated'), ('PENDING', 'Pending Assessment')], default='PENDING', help_text='Eligibility for mechanical thrombectomy.', max_length=15)),
                ('treatment_recommendation', models.TextField(blank=True, help_text='Recommended treatment plan based on guidelines.', null=True)),
                ('patient', models.ForeignKey(help_text='The patient associated with this assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.patient')),
            ],
            options={
                'verbose_name': 'Stroke Assessment',
                'verbose_name_plural': 'Stroke Assessments',
                'ordering': ['-assessment_time'],
            },
        ),
    ]
