# Generated by Django 5.2.1 on 2025-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_strokeassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='strokeassessment',
            name='current_anticoagulant_use',
            field=models.BooleanField(default=False, help_text='Current use of direct thrombin inhibitors or factor Xa inhibitors.'),
        ),
        migrations.AddField(
            model_name='strokeassessment',
            name='elevated_inr',
            field=models.BooleanField(default=False, help_text='INR > 1.7 (if on warfarin or other anticoagulants).'),
        ),
        migrations.AddField(
            model_name='strokeassessment',
            name='gi_urinary_hemorrhage',
            field=models.BooleanField(default=False, help_text='Recent gastrointestinal or urinary tract hemorrhage (within 21 days).'),
        ),
        migrations.AddField(
            model_name='strokeassessment',
            name='low_platelets',
            field=models.BooleanField(default=False, help_text='Platelet count < 100,000/mm³.'),
        ),
        migrations.AddField(
            model_name='strokeassessment',
            name='prior_stroke_head_trauma',
            field=models.BooleanField(default=False, help_text='History of prior stroke or serious head trauma in the last 3 months.'),
        ),
        migrations.AddField(
            model_name='strokeassessment',
            name='recent_surgery',
            field=models.BooleanField(default=False, help_text='Major surgery or serious trauma in the last 3 months.'),
        ),
    ]
